name: Run Tests with Coverage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure requirements.txt is in the root of your repository

      - name: Run Tests with Coverage
        run: |
          pytest --cov=app --cov-report=xml --cov-report=html

      - name: Upload Coverage Report
        if: success() # Only upload if the tests pass
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.xml
